/*
 * Content Management
 * The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FeedRecord
 */
public class FeedRecordTest {
    private final FeedRecord model = new FeedRecord();

    /**
     * Model tests for FeedRecord
     */
    @Test
    public void testFeedRecord() {
        // TODO: test FeedRecord
    }

    /**
     * Test the property 'feedId'
     */
    @Test
    public void feedIdTest() {
        // TODO: test feedId
    }

    /**
     * Test the property 'feedSource'
     */
    @Test
    public void feedSourceTest() {
        // TODO: test feedSource
    }

    /**
     * Test the property 'feedType'
     */
    @Test
    public void feedTypeTest() {
        // TODO: test feedType
    }

    /**
     * Test the property 'partnerId'
     */
    @Test
    public void partnerIdTest() {
        // TODO: test partnerId
    }

    /**
     * Test the property 'itemsReceived'
     */
    @Test
    public void itemsReceivedTest() {
        // TODO: test itemsReceived
    }

    /**
     * Test the property 'itemsSucceeded'
     */
    @Test
    public void itemsSucceededTest() {
        // TODO: test itemsSucceeded
    }

    /**
     * Test the property 'itemsFailed'
     */
    @Test
    public void itemsFailedTest() {
        // TODO: test itemsFailed
    }

    /**
     * Test the property 'itemsProcessing'
     */
    @Test
    public void itemsProcessingTest() {
        // TODO: test itemsProcessing
    }

    /**
     * Test the property 'feedStatus'
     */
    @Test
    public void feedStatusTest() {
        // TODO: test feedStatus
    }

    /**
     * Test the property 'feedDate'
     */
    @Test
    public void feedDateTest() {
        // TODO: test feedDate
    }

    /**
     * Test the property 'batchId'
     */
    @Test
    public void batchIdTest() {
        // TODO: test batchId
    }

    /**
     * Test the property 'modifiedDtm'
     */
    @Test
    public void modifiedDtmTest() {
        // TODO: test modifiedDtm
    }

}
