/*
 * Content Management
 * The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.IngestionErrorsIngestionErrorInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ItemDetailsItemIngestionStatusInnerIngestionErrors
 */
public class ItemDetailsItemIngestionStatusInnerIngestionErrorsTest {
    private final ItemDetailsItemIngestionStatusInnerIngestionErrors model = new ItemDetailsItemIngestionStatusInnerIngestionErrors();

    /**
     * Model tests for ItemDetailsItemIngestionStatusInnerIngestionErrors
     */
    @Test
    public void testItemDetailsItemIngestionStatusInnerIngestionErrors() {
        // TODO: test ItemDetailsItemIngestionStatusInnerIngestionErrors
    }

    /**
     * Test the property 'ingestionError'
     */
    @Test
    public void ingestionErrorTest() {
        // TODO: test ingestionError
    }

}
