/*
 * Content Management
 * The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ItemDetailsItemIngestionStatusInnerIngestionErrors;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ItemDetailsItemIngestionStatusInner
 */
public class ItemDetailsItemIngestionStatusInnerTest {
    private final ItemDetailsItemIngestionStatusInner model = new ItemDetailsItemIngestionStatusInner();

    /**
     * Model tests for ItemDetailsItemIngestionStatusInner
     */
    @Test
    public void testItemDetailsItemIngestionStatusInner() {
        // TODO: test ItemDetailsItemIngestionStatusInner
    }

    /**
     * Test the property 'martId'
     */
    @Test
    public void martIdTest() {
        // TODO: test martId
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'wpid'
     */
    @Test
    public void wpidTest() {
        // TODO: test wpid
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'ingestionStatus'
     */
    @Test
    public void ingestionStatusTest() {
        // TODO: test ingestionStatus
    }

    /**
     * Test the property 'ingestionErrors'
     */
    @Test
    public void ingestionErrorsTest() {
        // TODO: test ingestionErrors
    }

}
