/*
 * Content Management
 * The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FeedRecordResponseErrorsInner;
import com.konfigthis.client.model.ItemDetailsItemIngestionStatusInnerIngestionErrors;
import com.konfigthis.client.model.PartnerFeedResponseItemDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PartnerFeedResponse
 */
public class PartnerFeedResponseTest {
    private final PartnerFeedResponse model = new PartnerFeedResponse();

    /**
     * Model tests for PartnerFeedResponse
     */
    @Test
    public void testPartnerFeedResponse() {
        // TODO: test PartnerFeedResponse
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'feedId'
     */
    @Test
    public void feedIdTest() {
        // TODO: test feedId
    }

    /**
     * Test the property 'feedStatus'
     */
    @Test
    public void feedStatusTest() {
        // TODO: test feedStatus
    }

    /**
     * Test the property 'ingestionErrors'
     */
    @Test
    public void ingestionErrorsTest() {
        // TODO: test ingestionErrors
    }

    /**
     * Test the property 'itemsReceived'
     */
    @Test
    public void itemsReceivedTest() {
        // TODO: test itemsReceived
    }

    /**
     * Test the property 'itemsSucceeded'
     */
    @Test
    public void itemsSucceededTest() {
        // TODO: test itemsSucceeded
    }

    /**
     * Test the property 'itemsFailed'
     */
    @Test
    public void itemsFailedTest() {
        // TODO: test itemsFailed
    }

    /**
     * Test the property 'itemsProcessing'
     */
    @Test
    public void itemsProcessingTest() {
        // TODO: test itemsProcessing
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'itemDetails'
     */
    @Test
    public void itemDetailsTest() {
        // TODO: test itemDetails
    }

}
