/*
 * Content Management
 * The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ItemDetailsItemIngestionStatusInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * List of ingestion status details for items in the feed
 */
@ApiModel(description = "List of ingestion status details for items in the feed")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ItemDetails {
  public static final String SERIALIZED_NAME_ITEM_INGESTION_STATUS = "itemIngestionStatus";
  @SerializedName(SERIALIZED_NAME_ITEM_INGESTION_STATUS)
  private List<ItemDetailsItemIngestionStatusInner> itemIngestionStatus = null;

  public ItemDetails() {
  }

  public ItemDetails itemIngestionStatus(List<ItemDetailsItemIngestionStatusInner> itemIngestionStatus) {
    
    
    
    
    this.itemIngestionStatus = itemIngestionStatus;
    return this;
  }

  public ItemDetails addItemIngestionStatusItem(ItemDetailsItemIngestionStatusInner itemIngestionStatusItem) {
    if (this.itemIngestionStatus == null) {
      this.itemIngestionStatus = new ArrayList<>();
    }
    this.itemIngestionStatus.add(itemIngestionStatusItem);
    return this;
  }

   /**
   * The ingestion status of an individual item
   * @return itemIngestionStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ingestion status of an individual item")

  public List<ItemDetailsItemIngestionStatusInner> getItemIngestionStatus() {
    return itemIngestionStatus;
  }


  public void setItemIngestionStatus(List<ItemDetailsItemIngestionStatusInner> itemIngestionStatus) {
    
    
    
    this.itemIngestionStatus = itemIngestionStatus;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ItemDetails instance itself
   */
  public ItemDetails putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemDetails itemDetails = (ItemDetails) o;
    return Objects.equals(this.itemIngestionStatus, itemDetails.itemIngestionStatus)&&
        Objects.equals(this.additionalProperties, itemDetails.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemIngestionStatus, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemDetails {\n");
    sb.append("    itemIngestionStatus: ").append(toIndentedString(itemIngestionStatus)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("itemIngestionStatus");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ItemDetails
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ItemDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ItemDetails is not found in the empty JSON string", ItemDetails.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("itemIngestionStatus") != null && !jsonObj.get("itemIngestionStatus").isJsonNull()) {
        JsonArray jsonArrayitemIngestionStatus = jsonObj.getAsJsonArray("itemIngestionStatus");
        if (jsonArrayitemIngestionStatus != null) {
          // ensure the json data is an array
          if (!jsonObj.get("itemIngestionStatus").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `itemIngestionStatus` to be an array in the JSON string but got `%s`", jsonObj.get("itemIngestionStatus").toString()));
          }

          // validate the optional field `itemIngestionStatus` (array)
          for (int i = 0; i < jsonArrayitemIngestionStatus.size(); i++) {
            ItemDetailsItemIngestionStatusInner.validateJsonObject(jsonArrayitemIngestionStatus.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ItemDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ItemDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ItemDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ItemDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<ItemDetails>() {
           @Override
           public void write(JsonWriter out, ItemDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ItemDetails read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ItemDetails instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ItemDetails given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ItemDetails
  * @throws IOException if the JSON string is invalid with respect to ItemDetails
  */
  public static ItemDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ItemDetails.class);
  }

 /**
  * Convert an instance of ItemDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

